a= input("enter first number: ")
a=int(a)
b= input("enter second number: ")
b=int(b)
# print("sum of two numbers is ", a+b)
# print(" remainder when a divided by b", a%b)
# print(" a is greater than b or not = ", a>=b)
print("the average of two numbers =", (a+b)/2)
print("square of the number is ", a*a)