# s=set()
# num1=input("provide the number 1 \n")
# num2=input("provide the number 2 \n")
# num3=input("provide the number 3 \n")
# num4=input("provide the number 4 \n")
# num5=input("provide the number 5 \n")
# num6=input("provide the number 6 \n")
# num7=input("provide the number 7 \n")
# num8=input("provide the number 8 \n")
# s.add(num1)
# s.add(num2)
# s.add(num3)
# s.add(num4)
# s.add(num5)
# s.add(num6)
# s.add(num7)
# s.add(num8)
# print(s)

s={18, "18"}
print(s)
print(type(s))